import 'package:flutter/material.dart';

/// Registry of all MaterialIcons used across the application.
/// Explicit static references ensure Flutter's icon tree-shaker
/// never strips these icon glyphs during Windows / desktop release builds.
class IconRegistry {
  static const List<IconData> icons = [
    Icons.layers_rounded,
    Icons.cloud_done_rounded,
    Icons.cloud_off_rounded,
    Icons.sync_rounded,
    Icons.refresh_rounded,
    Icons.phone_callback_rounded,
    Icons.build_rounded,
    Icons.swap_horiz_rounded,
    Icons.inventory_2_rounded,
    Icons.receipt_long_rounded,
    Icons.help_outline_rounded,
    Icons.shopping_cart_rounded,
    Icons.tune_rounded,
    Icons.search_rounded,
    Icons.arrow_drop_down,
    Icons.add_rounded,
    Icons.person_rounded,
    Icons.lock_person_rounded,
    Icons.edit_rounded,
    Icons.delete_rounded,
    Icons.chevron_left_rounded,
    Icons.chevron_right_rounded,
    Icons.print_rounded,
    Icons.check_circle_rounded,
    Icons.visibility_rounded,
    Icons.filter_list_rounded,
    Icons.close_rounded,
    Icons.save_rounded,
    Icons.arrow_back_rounded,
    Icons.file_download_rounded,
    Icons.upload_file_rounded,
    Icons.dashboard_rounded,
    Icons.monetization_on_rounded,
    Icons.pie_chart_rounded,
    Icons.bar_chart_rounded,
    Icons.calendar_today_rounded,
    Icons.history_rounded,
    Icons.attach_money_rounded,
    Icons.qr_code_rounded,
    Icons.qr_code_scanner_rounded,
    Icons.done_rounded,
    Icons.cancel_rounded,
    Icons.error_outline_rounded,
    Icons.info_outline_rounded,
    Icons.warning_amber_rounded,
    Icons.more_vert_rounded,
    Icons.picture_as_pdf_rounded,
  ];
}
